### ISSUE TITLE
will the anonymous api last?

### ISSUE THREAD

**Issue by halower** [oelin/node-replicate#6]
this project is too nice, will it be a long-term maintenance project

**Comment by oelin** [comment]
If Replicate.com change their anonymous API, `node-replicate` will accommodate those changes. However, if they entirely disable their anonymous API, the project will probably be shelved.

So far they haven't announced any plans to take the anonymous endpoints offline though.

**Comment by booherbg** [comment]
Thank you. What are the terms of the anonymous API? Things are so abstract now I'm not even sure where / when this code is running :P

**Comment by oelin** [comment]
The anonymous API is a collection of endpoints which implement a subset of the functionalities provided by Replicate's authenticated API. For instance, you can run models, monitor pending predictions or cancel predictions. The models themselves run on high performance GPUs in the cloud. This client is for Node.js only (i.e. not the browser), so any code using `node-replicate` would probably run on your app's backend. Due to the a lack of CORS support for these anonymous endpoints, this client cannot be implemented client-side yet. Hope this helps!
